---
- hosts: all
  tasks:
    - name: Run show version on remote devices
      cisco.ios.ios_config:
        state: parsed
        get_config: True
      register: command_output
      
    - name: set running-config fact
      set_fact:
        running_config: "{{ command_output.stdout }}"
        cacheable: yes
