---
- name: Transfer firmware from AWX to Cisco switch
  hosts: all
  tasks:
    - name: Copy firmware to switch via SFTP
      ansible.netcommon.net_put:
        src: "{{ playbook_dir }}/firmware.bin"
        dest: bootflash:/cat9k_lite_iosxe.17.09.05.SPA.bin
        protocol: sftp
